bcgov/MOH-PPPP-Enrolment

- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
> Updated data stores for "Pay Patient" and "Pay Practitioner".

- pppp/package-lock.json
- pppp/src/views/pay-practitioner/HomePage.vue
> Add pay-practitioner copy

- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
Feature addition, pay practitioner claim count
> Add claim count functionality to pay practitioner

- pppp/src/views/pay-patient/MainFormPage.vue
> Pay Patient: Main form additions.

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/helpers/string.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
> Pay Patient: Review page.

- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
Adding content to main form for pay-practitioner
I've yet to add the new fields, this is just the existing ones so far
> Add main form content

- pppp/package-lock.json
- pppp/package.json
- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/MainFormPage.vue
> Pay Patient: Field types and validations.

- pppp/src/App.vue
- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/helpers/string.js
- pppp/src/helpers/url.js
- pppp/src/router/index.js
- pppp/src/router/routes.js
- pppp/src/router/step-routes.js
- pppp/src/services/api-service.js
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/HomePage.vue
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-patient/SubmissionErrorPage.vue
- pppp/src/views/pay-patient/SubmissionPage.vue
> Pay Patient: Added CSR routes.

- pppp/src/App.vue
> Setting dynamic page title.

- pppp/package-lock.json
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
Content additions and validation updates. 
Will add new routing in future PR
> Add validations and review page content

- pppp/src/store/modules/pay-patient-form.js
> Refactor to Pay Patient Vuex store module.

- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/HomePage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
- pppp/src/views/pay-practitioner/SubmissionErrorPage.vue
- pppp/src/views/pay-practitioner/SubmissionPage.vue
> Routing update

- pppp/package-lock.json
- pppp/package.json
- pppp/src/views/pay-patient/ClaimCountPage.vue
This fixes the `NumberSelect` component not working IE.
> Switch Pay Patient to use common lib `NumberSelect` component.

- pppp/src/App.vue
> Added CSR paths to stepper.

- pppp/package-lock.json
- pppp/package.json
> PPPP version bump (v0.1.1).

- pppp/src/components/Captcha.vue
- pppp/src/components/ConsentModal.vue
- pppp/src/views/pay-patient/HomePage.vue
- pppp/src/views/pay-practitioner/HomePage.vue
> Made consent modal visible, and added `captchaVerified` event to modal.

- pppp/package-lock.json
- pppp/package.json
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
> Pay Patient form validations.

- pppp/package-lock.json
- pppp/package.json
- pppp/src/components/ServiceLocationSelect.vue
- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
> Pay Patient validations.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.2).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/components/CorrespondenceAttachedMessage.vue
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
> Pay Patient/Pay Practitioner form updates.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.3).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Added date validation to "Pay Practitioner" form.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.4).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/helpers/select-options.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Added "Submission Code" validation.

- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-15: Increase max length of notes fields.

- pppp/package-lock.json
- pppp/package.json
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-6: Added motor vehicle accident component and validation.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.5).

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Updated "referred" first name entry.

- pppp/src/helpers/select-options.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-4: Added "correspondence attached" dropdown.

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/helpers/scroll.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-14: Scroll to section from Review page.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.6).

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/helpers/validators.js
- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-17, CLMWEBDE-5, and CLMWEBDE-18: Updated practitioner fields.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.7).

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.8).

- pppp/src/services/api-service.js
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
> Added JSON payload to API request methods.

- pppp/src/constants/select-options.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-3: Updated "Submission Code" option labels.

- pppp/src/helpers/form-helpers.js
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
> CLMWEBDE-4: Added new "Correspondence Attached" requirement.

- pppp/package-lock.json
- pppp/package.json
> PPPP Version bump (v0.1.9).

- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-23: Made "Location of Service" field required.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.10).

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/services/api-service.js
- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-18

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/services/api-service.js
- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
> CLMWEBDE-26

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.12).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-24: Force uppercase for Clarification Codes.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.13).

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Implemented CLMWEBDE-35 and CLMWEBDE-36.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.14).

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.15).

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.16).

- pppp/src/constants/select-options.js
> CLMWEBDE-3: Updated submission code option labels.

- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/views/LandingPage.vue
> Pay Practitioner: feedback updates.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.17).

- msp-service/src/index.js
- pppp/src/services/api-service.js
> API endpoint updates, and msp-service config.

- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
> CLMWEBDE-39: Updated Review page time labels.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.18).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/services/api-service.js
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-patient/SubmissionErrorPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
- pppp/src/views/pay-practitioner/SubmissionErrorPage.vue
> API service updates.

- pppp/src/store/modules/pay-patient-form.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/HomePage.vue
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/HomePage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-41, CLMWEBDE-42, and CLMWEBDE-43.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.19).

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.20).

- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-53, CLMWEBDE-56, and CLMWEBDE-57.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.21).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-48, CLMWEBDE-50, CLMWEBDE-54, and CLMWEBDE-58.

- pppp/src/helpers/validators.js
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-55 and CLMWEBDE-59.

- pppp/src/services/api-service.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-60: Fixed error label, and fixed PHN space removal in payload.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.22).

- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-61: Added min length to coverage pre-auth number.

- pppp/package-lock.json
- pppp/package.json
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Switch to `DigitInput` instead of `NumberInput` to force non-decimals.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.23).

- pppp/src/components/ContinueBar.vue
- pppp/src/components/ReviewTable.vue
- pppp/src/helpers/validators.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-65, CLMWEBDE-66, CLMWEBDE-68, and CLMWEBDE-69.

- pppp/src/constants/select-options.js
- pppp/src/helpers/validators.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-69: Specialty code white-list validation.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.24).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/helpers/validators.js
- pppp/src/store/states/pay-patient-form-dummy-data.js
- pppp/src/styles/styles.css
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/ReviewPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/ReviewPage.vue
> CLMWEBDE-71, CLMWEBDE-72, and CLMWEBDE-73.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.25).

- pppp/src/helpers/validators.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> CLMWEBDE-71: Added tip box to both forms.

- pppp/src/constants/select-options.js
- pppp/src/store/states/pay-practitioner-form-dummy-data.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Pay Practitioner server-side validation.

- pppp/src/components/ReviewTable.vue
- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/src/styles/styles.css
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/SubmissionPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/SubmissionPage.vue
> CLMWEBDE-72, CLMWEBDE-74, CLMWEBDE-75, and CLMWEBDE-80.

- pppp/package-lock.json
- pppp/package.json
> Common lib version bump (v1.0.49).

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.26).

- pppp/src/views/pay-patient/SubmissionErrorPage.vue
- pppp/src/views/pay-patient/SubmissionPage.vue
- pppp/src/views/pay-practitioner/SubmissionErrorPage.vue
- pppp/src/views/pay-practitioner/SubmissionPage.vue
> CLMWEBDE-81 and CLMWEBDE-83.

- pppp/package-lock.json
- pppp/src/App.vue
- pppp/src/components/ConsentModal.vue
- pppp/src/views/pay-patient/ClaimCountPage.vue
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/ClaimCountPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Accessibility

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.27).

- pppp/src/App.vue
> Consent modal display logic.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v0.1.28).

- pppp/package-lock.json
- pppp/package.json
> Version bump (v1.0.0).

- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
Changed the following validators to check for CSR before running for birthDate and serviceDate (pay patient and pay practitioner):
birthDatePastValidator, distantPastValidator, serviceDateFutureValidator
Should cover the requirements for CLMWEBDE-99, CLMWEBDE-96, and CLMWEBDE-102
> Csr date validations

- pppp/src/helpers/validators.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/tests/unit/helpers/validators.spec.js
- [] Tests for these changes were added (if applicable) (remaining tests are coming)
--Change MotorVehicleAccidentClaimNumberInput to regular Input (with maxLength and isUpperCaseForced)
--Add new motorVehicleAccidentClaimNumberMaskValidator to make up for the input filtering the component used to handle
--Add alphanumericValidator to vehicleAccidentClaimNumber to make up for filtering that the component used to handle
--Update aria-live error message to check mask validator
--Add unit tests for mask validator
--Fix facilityNumber to check CSR
> CSR facility number, motor vehicle

- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
> Birthdate validator fix.

- pppp/package-lock.json
- pppp/package.json
> Version bump (v1.0.1).

- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/tests/unit/views/pay-patient/MainFormPage.spec.js
- pppp/tests/unit/views/pay-practitioner/MainFormPage.spec.js
Unit tests for the Main Form page, pay patient and pay practitioner. Also some minor cleanup on the MainFormPage.vue pages to eliminate some console messages
All unit tests pass, e2e tests pass without problems, no errors on the console that I can see. 94% code coverage across the whole project now, including 97% for each MainFormPage.vue component.
> Main form unit tests

- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/SubmissionPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/SubmissionPage.vue
- pppp/tests/e2e/specs/happyPathPatient-CSR.spec.js
- pppp/tests/e2e/specs/happyPathPatient.spec.js
- pppp/tests/e2e/specs/happyPathPractitioner-CSR.spec.js
- pppp/tests/e2e/specs/happyPathPractitioner.spec.js
- pppp/tests/unit/views/pay-patient/MainFormPage.spec.js
- pppp/tests/unit/views/pay-practitioner/MainFormPage.spec.js
--Fix reset form bug (add set facility number commit to store modules to ensure that field gets cleared
--Fix broken tests that happened on deploy-phase-2 merge (birthDatePastValidator now checks for CSR, birth date validator fix tests added, dayTo now sets to null in tests where dayFrom is changed to prevent real life date-based test failures)
--Add Start New Form button to pay patient and pay practitioner
--Add  end-to-end tests to verify Start New Form button functionality
All unit and e2e tests pass, no weird console logs
> Feature/Bug: Add Start New Form button, fix form reset bug

- pppp/src/helpers/validators.js
- pppp/src/store/modules/pay-practitioner-form.js
- pppp/src/views/pay-patient/MainFormPage.vue
- pppp/src/views/pay-patient/SubmissionPage.vue
- pppp/src/views/pay-practitioner/MainFormPage.vue
- pppp/src/views/pay-practitioner/SubmissionPage.vue
- pppp/tests/e2e/specs/happyPathPatient-CSR.spec.js
- pppp/tests/e2e/specs/happyPathPatient.spec.js
- pppp/tests/e2e/specs/happyPathPractitioner-CSR.spec.js
- pppp/tests/e2e/specs/happyPathPractitioner.spec.js
- pppp/tests/unit/helpers/validators.spec.js
- pppp/tests/unit/views/pay-patient/MainFormPage.spec.js
- pppp/tests/unit/views/pay-practitioner/MainFormPage.spec.js
Merging everything into main so we can deploy to test
> Deploy phase 2: Merge into main

- pppp/package-lock.json
- pppp/package.json
> Version bump (v1.1.0)

- pppp/package-lock.json
- pppp/package.json
Version bump. Update to package.json and package-lock.json
> Version bump 1.1.1

- pppp/package-lock.json
> Run `npm audit fix`.

- pppp/package-lock.json
- pppp/package.json
> PPPP: version bump (v1.1.2).

- pppp/package-lock.json
- pppp/package.json
Chore.
GitHub has deprecated the anonymous usage of the "git://" protocol when specifying them in dependencies. I've updated this to "https://" instead. I've also updated the PPPP frontend to use the latest version of the Vue common library, which has been fixed to "https://" as well.
Also disabled unit tests as they were running out of memory in the GitHub action.
> Dependency updates.

- pppp/src/views/pay-practitioner/MainFormPage.vue
Forces diagnostic code to be all caps so lowercase codes aren't rejected
> Fix missing diagnostic force uppercase

- pppp/package-lock.json
- pppp/package.json
> Version bump to 1.1.3

- .github/workflows/pppp-web.yaml
- pppp/.eslintrc.js
- pppp/openshift/templates/build.yaml
- pppp/package-lock.json
- pppp/package.json
- pppp/src/components/Captcha.vue
- pppp/src/components/ReviewTable.vue
- pppp/src/components/pay-patient/ReviewTableList.vue
- pppp/src/components/pay-practitioner/ReviewTableList.vue
- pppp/tests/unit/components/Captcha.spec.js
- pppp/tests/unit/components/ConsentModal.spec.js
- pppp/tests/unit/components/ProgressBar.spec.js
- pppp/tests/unit/components/ReviewTableListPatient.spec.js
- pppp/tests/unit/components/ReviewTableListPractitioner.spec.js
- pppp/tests/unit/helpers/url.spec.js
- pppp/tests/unit/helpers/validators.spec.js
- pppp/tests/unit/router/routes.spec.js
- pppp/tests/unit/services/api-service.spec.js
- pppp/tests/unit/services/page-state-service.spec.js
- pppp/tests/unit/services/spa-env-service.spec.js
- pppp/tests/unit/views/pay-patient/ClaimCountPage.spec.js
- pppp/tests/unit/views/pay-patient/MainFormPage.spec.js
- pppp/tests/unit/views/pay-practitioner/ClaimCountPage.spec.js
- pppp/tests/unit/views/pay-practitioner/MainFormPage.spec.js
Note: when I ran `npm run lint` it changed a bunch of stuff in unit test files. There's still a bunch of linting warnings, but we don't need to fix those right away.
> "node-ipc" vulnerability fixes.

- pppp/package-lock.json
- pppp/package.json
> PPPP: version bump (v1.1.4).

- pppp/package-lock.json
- pppp/package.json
> Version bump from 1.1.4 -> 1.1.5

- pppp/package-lock.json
- pppp/package.json
> PPPP: version bump (v1.1.6).

- pppp/package-lock.json
- pppp/package.json
- pppp/src/views/pay-patient/HomePage.vue
- pppp/src/views/pay-practitioner/HomePage.vue
- pppp/tests/unit/views/pay-practitioner/MainFormPageValidateFieldsPublic.spec.js
Bug fix
Hoping this will work, can't really tell until it's been deployed to dev
> Fix pppp maintenance page

- pppp/cypress.config.js
- pppp/src/constants/diagnostic-codes.js
- pppp/tests/unit/views/pay-practitioner/MainFormPageValidateFieldsPublic.spec.js
Adds new diagnostic code to list. Also fixes a lingering unit test issue
Manually checked in the frontend that L23 works as a diagnostic code now. Unit tests all pass after the change. E2E tests all pass. Npm run build works. Npm run lint passes (apart from a few intentionally skipped tests).
> Diagnostic code L23

- pppp/package-lock.json
- pppp/package.json
> Version bump from 1.1.8 -> 1.1.9

- .github/workflows/pppp-web.yaml
- pppp/package.json
- pppp/tests/e2e/specs/happyPathPatient-CSR.cy.js
- pppp/tests/e2e/specs/happyPathPatient.cy.js
- pppp/tests/e2e/specs/happyPathPractitioner-CSR.cy.js
- pppp/tests/e2e/specs/happyPathPractitioner.cy.js
- pppp/tests/e2e/specs/optionalField--payPatientCSR.cy.js
- pppp/tests/e2e/specs/optionalField--payPractitionerCSR.cy.js
Updates E2E tests to be easier to apply to the TEST environment if needed
Adds a variable for the testUrl to make it more intuitive to swap out
Adds a headless E2E check to the build workflow
> Test environment E2E testing updates

- splunk-forwarder/src/splunklogger.js
Update wording from "Splunk" to "Api-Token" so it works with Dynatrace
Npm run build passes. No testing suite exists for this microservice, so no tests were run. The plan for this build is to deploy it to dev, see if it works as intended with Dynatrace, and iterate on it if it doesn't.
> Update Splunk Forwarder formatting

- msp-service/src/index.js
- splunk-forwarder/src/splunklogger.js
Splunk to dynatrace migration stuff, cleanup (some of this was done earlier when I was experimenting, but this should complete that process)
`npm run build` works in Splunk Forwarder and MSP-service. `npm run start` was NOT verified due to environment variables needing to be passed down.
> Splunk to dynatrace migration
